/**
 * Shared compendium pack configuration — the single source of truth for the
 * pack build (build-packs.mjs) and the validator (validate.mjs), so the two
 * can never drift on pack names, id derivation, or source layout.
 *
 * Source layout: one JSON file per document under packs/_source/<file>/, each
 * with a human-friendly `key` slug (no ids). Ids are derived deterministically
 * from (pack, key), so rebuilding never reshuffles them.
 */
import { createHash } from "node:crypto";
import { readFileSync, readdirSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

export const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
export const SRC = join(ROOT, "packs", "_source");
export const OUT = join(ROOT, "packs");

/**
 * file → output pack, document class & subtype. Must match system.json packs[]
 * (and an Item/Actor subtype must be declared in system.json documentTypes).
 * All three are generated by tools/gen-pack-source.mjs from the game data
 * (module/config.mjs, book/src/towns.json): never edit their source by hand.
 *  - entities: the eight Entities, as New Entity makes them (Chapter 2);
 *  - tables:   the book's random tables (Chapters 2, 6 and 8);
 *  - journal:  the three premade towns (Chapter 9) and a guide to the system's tools.
 */
export const PACKS = [
  { file: "entities", out: "entities", collection: "actors", type: "Actor", subtype: "entity" },
  { file: "tables", out: "tables", collection: "tables", type: "RollTable", subtype: null },
  { file: "journal", out: "journal", collection: "journal", type: "JournalEntry", subtype: null },
];

/** Icons from Foundry core for documents that don't name their own. */
export const TABLE_ICON = "icons/svg/d20-grey.svg";
export const RESULT_ICON = "icons/svg/d20-black.svg";

/** The embedded documents a source doc carries (journal pages, table results), for id scans. */
export function embeddedOf(def, raw) {
  if (def.type === "JournalEntry") return raw.pages ?? [];
  if (def.type === "RollTable") return raw.results ?? [];
  return [];
}

/** Deterministic 16-char alphanumeric id from a namespace + key (sha256 hex prefix). */
export function makeId(...parts) {
  return createHash("sha256").update(parts.join("::")).digest("hex").slice(0, 16);
}

/**
 * Read a pack's source: one JSON file per document under packs/_source/<name>/,
 * returned as an array sorted by filename (deterministic for reproducible builds).
 */
export function readSource(file) {
  const dir = join(SRC, file);
  if (!existsSync(dir)) throw new Error(`pack source folder missing: packs/_source/${file}/`);
  return readdirSync(dir)
    .filter(f => f.endsWith(".json"))
    .sort()
    .map(f => JSON.parse(readFileSync(join(dir, f), "utf8")));
}

const manifest = JSON.parse(readFileSync(join(ROOT, "system.json"), "utf8"));

/** Provenance stamped on every document. */
export const STATS = {
  // Oldest core whose schema this data fits: v13 refuses to import documents
  // stamped with a newer core, and v14 migrates up from here.
  coreVersion: "13.351",
  systemId: manifest.id,
  systemVersion: manifest.version,
  createdTime: null,
  modifiedTime: null,
  lastModifiedBy: null,
  compendiumSource: null,
  duplicateSource: null,
  exportSource: null
};

/**
 * Turn one of our source docs into a CLI-ready document (deterministic `_id`,
 * `_key`, `_stats`, inline embedded pages). Shared by the build and validator.
 */
export function toCliDoc(def, raw, index) {
  const id = makeId(def.out, raw.key);
  const sort = (index + 1) * 100;

  if (def.type === "JournalEntry") {
    return {
      _id: id,
      _key: `!journal!${id}`,
      name: raw.name,
      pages: (raw.pages ?? []).map((page, p) => {
        const pid = makeId(def.out, raw.key, page.key ?? String(p));
        const out = {
          _id: pid,
          _key: `!journal.pages!${id}.${pid}`,
          name: page.name,
          type: page.type ?? "text",
          title: page.title ?? { show: true, level: 1 },
          text: page.text ?? { format: 1, content: "" },
          sort: (p + 1) * 100,
          ownership: { default: -1 },
          flags: {},
          _stats: STATS
        };
        // An image page: the picture's path (systems/<id>/…) and its caption.
        if (page.src) { out.src = page.src; out.image = page.image ?? { caption: "" }; }
        return out;
      }),
      categories: [],
      folder: null,
      sort,
      ownership: { default: 0 },
      flags: {},
      _stats: STATS
    };
  }

  if (def.type === "RollTable") {
    // v13+ TableResult: a text result keeps its words in `description` (HTML) and
    // leaves `name` empty, as Foundry's own systems do; `range` is the roll totals
    // that draw it. Tables draw with replacement: the book rerolls a repeat by
    // hand, and drawing without it would have to mark results in a locked pack.
    return {
      _id: id,
      _key: `!tables!${id}`,
      name: raw.name,
      img: raw.img ?? TABLE_ICON,
      description: raw.description ?? "",
      results: (raw.results ?? []).map((r, k) => {
        const rid = makeId(def.out, raw.key, r.key ?? String(k));
        return {
          _id: rid,
          _key: `!tables.results!${id}.${rid}`,
          type: "text",
          name: r.name ?? "",
          description: r.description ?? "",
          img: r.img ?? RESULT_ICON,
          documentUuid: null,
          weight: r.weight ?? 1,
          range: r.range,
          drawn: false,
          flags: {},
          _stats: STATS
        };
      }),
      formula: raw.formula,
      replacement: true,
      displayRoll: true,
      folder: null,
      sort,
      ownership: { default: 0 },
      flags: {},
      _stats: STATS
    };
  }

  const doc = {
    _id: id,
    _key: `!${def.collection}!${id}`,
    name: raw.name,
    type: def.subtype,
    img: raw.img,
    system: raw.system ?? {},
    effects: [],
    folder: null,
    sort,
    ownership: { default: 0 },
    flags: {},
    _stats: STATS
  };
  if (def.type === "Actor") {
    doc.items = [];
    // null (not "") disables a token bar; "" would be cleaned back to the
    // system's primaryTokenAttribute. Override per pack once actors exist.
    // actorLink: a dragged-in Entity's tokens change the actor the raid tracks.
    doc.prototypeToken = { actorLink: true, bar1: { attribute: null }, bar2: { attribute: null } };
  }
  return doc;
}
